### ISSUE TITLE
EPIC: Inspector can select a project and view related infomation data

### ISSUE THREAD

**Issue by patevs** [patevs/ng-info#3]
- [x] UI: Inspector selects a project
- [x] SS: Project information is retrieved from the server
- [x] UI: Project information is displayed to user

**Comment by patevs** [comment]
DONE

**Comment by patevs** [comment]
Close
