### ISSUE TITLE
EPIC: Manager can add/archive roads

### ISSUE THREAD

**Issue by patevs** [patevs/ng-info#4]
- [x] UI: Manager selects a road
- [x] SS: Road information is retrieved from server
- [x] UI: Road information is displayed to user
- [x] SS: Selected road is added/removed from road directory

**Comment by patevs** [comment]
DONE
